annotation_folder = "./annotations"
asset_folder = "./assets"

model = "yolov10n.pt"
model_name = "coco_yolov11n"
conf_file = "config.yaml"
run_name = "yolov11n"
epochs = 2
device = "0"
save_dir = "./model"
mlflow_local_path = "requirements.txt"
mlflow_artifact_path = "environment"