# picsellia
api_token = "d6551b4286b10efe8b832e98b64efs"
dataset_version_id = "01daz123-e7ee-799f-8b98-83f8d56qsdq"

# bentoml
MLFLOW_TRACKING_URI = "http://localhost:5001"
MLFLOW_DEFAULT_ARTIFACT_ROOT = "s3://mlflow/mlflow-artifacts/"
AWS_ACCESS_KEY_ID = "minioadmin"
AWS_SECRET_ACCESS_KEY = "minioadmin"
