annotation_folder = "./annotations"
asset_folder = "./assets"

model = "yolov10n.pt"
model_name = "coco_yolov11n"
conf_file = "config/config.yaml"
run_name = "yolov11n"
mlflow_local_path = "requirements.txt"
mlflow_artifact_path = "environment"
dataset_folder = "./dataset"
