name: "Python tests"

on:
  pull_request:
    types: [ opened, synchronize ] # Run on PR open and PR push

jobs:
  test:
    runs-on: ubuntu-latest # type de runner ubuntu/windows/macOS il y plusieurs versions

    steps:
    - uses: actions/checkout@v4 # Check out the repository

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --cov=./ --cov-report=xml
